i3-resurrect restore -w "10"
i3-resurrect restore -w "9"
i3-resurrect restore -w "8"
i3-resurrect restore -w "7"
i3-resurrect restore -w "6"
i3-resurrect restore -w "5"
i3-resurrect restore -w "4"
i3-resurrect restore -w "3"
i3-resurrect restore -w "2"
i3-resurrect restore -w "1"
sleep 4
i3-resurrect rm -w "1"
i3-resurrect rm -w "2"
i3-resurrect rm -w "3"
i3-resurrect rm -w "4"
i3-resurrect rm -w "5"
i3-resurrect rm -w "6"
i3-resurrect rm -w "7"
i3-resurrect rm -w "8"
i3-resurrect rm -w "9"
i3-resurrect rm -w "10"
exit